site_name: eryz's notes
site_url: https://gabriellagloria.github.io/eryz-notes
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - blog.post_excerpt
  palette: 
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: src/Kirby_Nintendo.png
  favicon: src/Kirby_Nintendo.png

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      post_excerpt: required
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  # - About: 
  #     - About me: about/about.md
  # - Tags: tags.md
  - Blog:
      - Highschool: blog/posts/Highschool.md
      - Uni: blog/posts/Uni.md
      - CP: blog/posts/CP.md
  - Notes:
      - Buffer Overflow and Format String: notes/posts/buffer.md
      - Combinatorics and Theorems: notes/posts/combin.md
      - Common Series: notes/posts/series.md
      - Recurrence Relations: notes/posts/recurrence.md

  - NUS:
      - Mods: NUS/mods.md
      - CS1010: NUS/CS1010.md
      - CS1231S: NUS/CS1231S.md
      - CS2030S: NUS/CS2030S.md
      - CS2040S: NUS/CS2040S.md
      - CS2100: NUS/CS2100.md
      - CS2105: NUS/CS2105.md
      - CS2106: NUS/CS2106.md
      - CS2107: NUS/CS2107.md
      - CS2109S: NUS/CS2109S.md
  - CTF:
      - HTB:
          - Starting-Point:
              - Vaccine: CTF/HTB/Starting-Point/Vaccine.md
              - Unified: CTF/HTB/Starting-Point/Unified.md
              - Included: CTF/HTB/Starting-Point/Included.md
          - Machines:
              - Support: CTF/HTB/Machines/Support.md
              - Broker: CTF/HTB/Machines/Broker.md
              - Headless: CTF/HTB/Machines/Headless.md

repo_url: https://github.com/GabriellaGloria/eryz-notes
repo_name: GabriellaGloria/eryz-notes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex
  - toc:
      permalink: true


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js
  # - js/reload.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css

